environment:
  matrix:
  - job_name: Windows
    appveyor_build_worker_image: Visual Studio 2019
    job_group: Build
  - job_name: Linux
    appveyor_build_worker_image: Ubuntu
    job_group: Build
  - job_name: Pack
    appveyor_build_worker_image: Visual Studio 2019
    job_depends_on: Build
  - job_name: Deploy
    job_depends_on: Pack
version: 1.0-{build}
for:
-
  matrix:
    only:
      - job_name: Windows
        job_group: Build
  build_script:
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake -T v142,host=x64 -G "Visual Studio 16 2019" -A Win32 ..
    - cd ..
    - cmake --build build --config Release --parallel
  artifacts:
    - path: 'build\*.dll'
-
  matrix:
    only:
      - job_name: Linux
        job_group: Build
  install:
    - sudo apt-get update
    - sudo apt-get --assume-yes install gcc-multilib g++-multilib
  build_script:
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=cmake/linux-i686.cmake -DCMAKE_BUILD_TYPE=Release ..
    - cd ..
    - cmake --build build --config Release --parallel
  artifacts:
    - path: 'build/*.so'
-
  matrix:
    only:
      - job_name: Pack
  build_script:
    - ps: >-
        $baseArtifactsFolder = "modules";
        $localArtifactsLocation = Join-Path $baseArtifactsFolder -ChildPath $env:appveyor_project_name;
        
        New-Item $localArtifactsLocation -ItemType Directory | Out-Null;
        
        $buildJobNames = @("Windows", "Linux");
        
        $currentBuildInfo = Invoke-RestMethod -Method Get -Uri "$env:appveyor_url/api/projects/$env:appveyor_account_name/$env:appveyor_project_slug/builds/$env:appveyor_build_id";
        
        foreach ($job in $currentBuildInfo.build.jobs) {
            if (-not ($job.name -in $buildJobNames)) {
                continue;
            }
            if (-not ($job.status -eq "success")) {
                throw;
            }
            
            $artifacts = Invoke-RestMethod -Method Get -Uri "$env:appveyor_url/api/buildjobs/$($job.jobId)/artifacts";
            
            foreach ($artifact in $artifacts) {
                $localArtifactPath = Join-Path $localArtifactsLocation -ChildPath $(Split-Path $artifact.fileName -Leaf);
                
                Invoke-RestMethod -Method Get -Uri "$env:appveyor_url/api/buildjobs/$($job.jobId)/artifacts/$($artifact.fileName)" -OutFile $localArtifactPath;
            }
        }
                
        Compress-Archive "$($env:appveyor_project_name)_$env:appveyor_build_version.zip" -DestinationPath "$($env:appveyor_project_name).zip";
  artifacts:
    - path: '*.zip'
-
  matrix:
    only:
      - job_name: Deploy    
  deploy:
    - provider: GitHub
      auth_token:
        secure: QDEGzc09i3TjexbQdbxWkOIfYdIkoFZDOyG4e+uFywRQQ5JDuyO3eFPW9dAlf+5u
      artifact: amxx-debugger-server.zip